{{-- <script defer src="https://usgmindray-css.vercel.app/js/jquery.min.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/bootstrap.min.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/swiper-bundle.min.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/carousel.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/bootstrap-select.min.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/wow.min.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/main.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/font-awesome.all.min.js"></script>
<script defer src="https://usgmindray-css.vercel.app/js/toastify.js"></script> --}}

<script defer src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script defer src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script defer src="{{ asset('assets/js/swiper-bundle.min.js') }}"></script>
<script defer src="{{ asset('assets/js/carousel.js') }}"></script>
<script defer src="{{ asset('assets/js/bootstrap-select.min.js') }}"></script>
<script defer src="{{ asset('assets/js/wow.min.js') }}"></script>
<script defer src="{{ asset('assets/js/main.js') }}"></script>
<script defer src="{{ asset('assets/js/font-awesome.all.min.js') }}"></script>
<script defer src="{{ asset('assets/js/toastify.js') }}"></script>
